### ISSUE TITLE
Lab 2 Step 4/5

### ISSUE THREAD

**Issue by dp018** [Xilinx/SDSoC-Tutorials#12]
In lab 1 the user will need to write out a HDF. Lab 2 step 4/5 says
Click Add New DSA/HDF….

In the Add New DSA/HDF dialog, navigate to the HDF exported in Lab 1.

Lab 1 needs to add in the step at the end. File -> Export Hardware (Local to project)

**Comment by amantalwar04** [comment]
Updated topic as suggested. Closing the issue.
