### ISSUE TITLE
Error in step 2 of Lab 2: Performance Estimation

### ISSUE THREAD

**Issue by greedyhao** [Xilinx/SDSoC-Tutorials#14]
Error occur 
when I do the step 2 of Lab 2: Performance Estimation

sds.log
`
...
ERROR: [VPL 60-399] vivado failed, please see log file for detail: '/home/greedyhao/Projects/fpga/sdx-2018-2/lab2_2/Release/_sds/p0/vivado/vivado.log'
ERROR: [VPL 60-806] Failed to finish platform linker
...
`
vivado.log
`
...
couldn't change working directory to "prj/prj.sim/sim_1/behav/xsim": no such file or directory
    while executing
"cd $project_name/$project_name.sim/sim_1/behav/$simulatorSelected"
    (procedure "hw_em_common_util::generate_simulation_scripts_and_compile_u..." line 49)
    invoked from within
"hw_em_common_util::generate_simulation_scripts_and_compile_unip $config_info"
    (file "/home/greedyhao/Projects/fpga/sdx-2018-2/lab2_2/Release/_sds/p0/vivado/ipirun.tcl" line 192)
...
`

**Comment by sgrace-xlnx** [comment]
Hi,

This may be caused due to memory issues of the machine. Can you provide specs of the machine you're running on? Generally, anything below 16GB of RAM may run into this issue.

**Comment by greedyhao** [comment]
I got it.

The RAM of my computer is only 8GB.
