### ISSUE TITLE
Error while launching program - Lab 6 (getting start tut.)

### ISSUE THREAD

**Issue by tuanho27** [Xilinx/SDSoC-Tutorials#15]
Hello,

After setting and creating the project for lab 6, I try to load the debug (Debug As > Launch on Hardware)
But I face with an error (as the image). Is there any idea for this?
![image](https://user-images.githubusercontent.com/22056468/49783570-c89eeb00-fd4c-11e8-9279-14b7723a8d21.png)

Thanks,
TuanH

**Comment by ErinTruax** [comment]
Assigned for investigation.

**Comment by tuanho27** [comment]
Hi, thanks 
The answer here:
https://forums.xilinx.com/t5/SDSoC-Environment-and-reVISION/Error-while-launching-program-Standalone-Debugger/m-p/922373#M3289
