### ISSUE TITLE
Is the custom platform created and added in the repository in lab 3 able to be used in a new workspace? 

### ISSUE THREAD

**Issue by peter2chang** [Xilinx/SDSoC-Tutorials#22]
Hi,
As I followed along lab 3 from step 1 through step 6, there is no issue to add a custom platform to repository then selected this custom platform in step 6 as a platform type for sdx_app1 project. 
After lab3, I created a new workspace for a different lab, and then I was not able to find the custom platform name created in lab 3 from the platform list for the new project. I am not sure if it is because the workspace is different. Now should I use the steps in lab 3 to create a new platform with the files stored in staging area from lab 2, and then generate the platform and add it into repository in current workspace again? Or is there any easy way to do it? Thanks in advance!

**Comment by randyh62** [comment]
Hi, When you change the workspace, the platform repository changes with it.

**Comment by peter2chang** [comment]
Hi Randy,
Thank you for your reply. I found the custom platform can be added by clicking the “add custom platform” button, and then just specify the directory to where my custom platform *.xpfm file resides.  
![repository1](https://user-images.githubusercontent.com/20788714/54811824-90506680-4cc4-11e9-933f-56434280571e.jpg)
