### ISSUE TITLE
How to get zynq7_ board [costom] platform?

### ISSUE THREAD

**Issue by microlijun** [Xilinx/SDSoC-Tutorials#27]
Hi, I see there is a zynq7_ board [costom] platform in the tutorial of Migrate OpenCV to xfOpenCV .  Where can I download it?

**Comment by randyh62** [comment]
The zynq7_board is a custom board that is built as part of the SDSoC Environment Tutorial: Platform Development in the 2018.2 release. The tutorial has been updated in 2018.3 to make a zcu102_board platform instead.

**Comment by microlijun** [comment]
> 
> 
> The zynq7_board is a custom board that is built as part of the SDSoC Environment Tutorial: Platform Development in the 2018.2 release. The tutorial has been updated in 2018.3 to make a zcu102_board platform instead.

Hi， @randyh62 
Can I use the zynq7_ board [costom] platform with ZedBoard? Since it is same family and parts as ZC702 board.

**Comment by randyh62** [comment]
I am not clear what you are asking. The zynq7_board that you are building in the Platform Development Tutorial is based on the standard zc702 platform that is provided as part of the SDSoC installation. You cannot use this platform for the ZedBoard. However, there is also a "zed" platform provided in the SDSoC installation. You can use that platform as a starting point for customization following the approach define in the Platform Development Tutorial.

**Comment by microlijun** [comment]
Hi, @randyh62 
I am migrating my opencv application to xfopencv by SDSoC. I followed the tutorial and successfully build it with zcu102 reVISION , but  I don't have a zcu102 board, only have a zedboard. I tried to use zed as the platform, but the build failed. So I am asking is there a zed reVISION I can download and use? Or what is the right way to this task?

Build log file is shown below:

`(c)Copyright 2012-2018 Xilinx, Inc. All Rights Reserved.`
`#-----------------------------------------------------------`
`# Tool version  : sds++ 2018.2 SW Build 2258646 on Thu Jun 14 20:03:40 MDT 2018`
`# Start time    : Thu Apr 04 14:46:18 UTC 2019`
`# Command line  : sds++ -Wall -O3 -I../src -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/lib/gcc/aarch64-linux-gnu/7.2.1/include-fixed -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/lib/gcc/aarch64-linux-gnu/7.2.1/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1/backward -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1/aarch64-linux-gnu -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1 -c -fmessage-length=0 -MTsrc/colordetect_accel.o -Wno-overloaded-virtual -Wno-unused-label -Wno-strict-overflow -Wno-uninitialized -Wno-unused-function -Wno-unused-variable -Wno-unknown-attributes -Wno-unused-local-typedefs -Wno-sign-compare -mstrict-align -hls-target 1 -MMD -MP -MFsrc/colordetect_accel.d -MTsrc/colordetect_accel.o -o src/colordetect_accel.o ../src/colordetect_accel.cpp -sds-sys-config linux -sds-proc linux -sds-pf zed'
`# Log file      : /home/jun/workspace_sdx/colordetect_zed/Release/_sds/reports/sds_colordetect_accel.log'
`# Journal file  : /home/jun/workspace_sdx/colordetect_zed/Release/_sds/reports/sds_colordetect_accel.jou'
`# Report file   : /home/jun/workspace_sdx/colordetect_zed/Release/_sds/reports/sds_colordetect_accel.rpt'
`#-----------------------------------------------------------'

Create data motion intermediate representation
/home/jun/Programs/Xilinx2018.2/SDx/2018.2/bin/clang_wrapper -I../src -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/lib/gcc/aarch64-linux-gnu/7.2.1/include-fixed -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/lib/gcc/aarch64-linux-gnu/7.2.1/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1/backward -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1/aarch64-linux-gnu -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch64/lin/aarch64-linux/aarch64-linux-gnu/include/c++/7.2.1 -Wall -fmessage-length=0 -Wno-overloaded-virtual -Wno-unused-label -Wno-strict-overflow -Wno-uninitialized -Wno-unused-function -Wno-unused-variable -Wno-unknown-attributes -Wno-unused-local-typedefs -Wno-sign-compare -mstrict-align -MMD -MP -D __SDSCC__ -target arm-linux-gnueabihf -mcpu=cortex-a9 -mfpu=vfpv3 -mfloat-abi=hard -O0 -g     -I /home/jun/Programs/Xilinx2018.2/SDx/2018.2/target/aarch32-linux/include  -D HLS_NO_XIL_FPO_LIB  -I /home/jun/Programs/Xilinx2018.2/Vivado/2018.2/include   -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/7.2.1 -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/7.2.1/arm-linux-gnueabihf -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include/c++/7.2.1/backward -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/lib/gcc/arm-linux-gnueabihf/7.2.1/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/lib/gcc/arm-linux-gnueabihf/7.2.1/include-fixed -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/include -I/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/arm-linux-gnueabihf/libc/usr/include  -std=c++11 -emit-llvm -S /home/jun/workspace_sdx/colordetect_zed/src/colordetect_accel.cpp -o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/.llvm/src/colordetect_accel.s
/home/jun/Programs/Xilinx2018.2/Vivado/2018.2/include/ap_int_special.h:99:1: warning: 'complex' defined as a struct template here but previously declared as a class template [-Wmismatched-tags]
struct complex<ap_int<_AP_W> > {
^
/home/jun/Programs/Xilinx2018.2/Vivado/2018.2/include/ap_int_special.h:71:24: note: did you mean struct here?
template<typename _Tp> class complex;
                       ^~~~~
                       struct
../src/colordetect_accel.hpp:3:10: fatal error: 'common/xf_common.h' file not found
#include "common/xf_common.h"
         ^
ERROR: [SdsCompiler 83-5005] clang exited with non-zero code processing /home/jun/workspace_sdx/colordetect_zed/src/colordetect_accel.cpp
sds++ log file saved as /home/jun/workspace_sdx/colordetect_zed/Release/_sds/reports/sds_colordetect_accel.log
ERROR: [SdsCompiler 83-5004] Build failed
sds++ completed at Thu Apr 04 14:46:22 UTC 2019

**Comment by sgrace-xlnx** [comment]
Hi @microlijun 

You'll have to create a specific platform for the Zedboard. WIth SDSoC providing it, you can follow tutorials and guides on how to do it via UG1146. Generally, most of the work would be on the PetaLinux build of it since that would require OpenCV to be included as well as xfOpenCV.

Thanks
Steve
