### ISSUE TITLE
Error building xfOpencv application using Zedboard

### ISSUE THREAD

**Issue by microlijun** [Xilinx/SDSoC-Tutorials#29]
Hi, I'm trying to migrate my opencv application to xfopencv. I already built it with zcu102 revision platform, but when I transfer to  zedboard, error shown as follow.

'' ERROR: [SYNCHK 200-79] Cannot find the top function 'w0_xf_boxFilter' in the design. Possible causes are: (1) the top function name is misspelled; (2) the top function is nonexistent or declared as static.
ERROR: [HLS 200-70] Synthesizability check failed.''

log file attached here:
[sds_guided_filter.log](https://github.com/Xilinx/SDSoC-Tutorials/files/3317979/sds_guided_filter.log)

My setting is as follow:
![image](https://user-images.githubusercontent.com/29748336/59978000-cba15080-95a5-11e9-9a05-78949838b244.png)

![image](https://user-images.githubusercontent.com/29748336/59978008-ed023c80-95a5-11e9-8bff-26d3fea0dd61.png)
/usr/local/arm/opencv-install/include/opencv  is a cross compilied OpenCv.
![image](https://user-images.githubusercontent.com/29748336/59978023-030ffd00-95a6-11e9-895d-86f36592d70e.png)

This is my source file. Could anyone help me build it? 
Thanks.

**Comment by microlijun** [comment]
I also tried to build an colordetect example from xfopencv with same setting. Errors shown as follow:

Preliminary link application ELF
arm-linux-gnueabihf-g++    /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_rgb2hsv_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_colorthresholding_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_dilation_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_erosion_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/src/xf_colordetect_tb.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_colordetect_accel.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/portinfo.o -L/usr/local/arm/opencv-install/lib -lopencv_videoio -lopencv_core -lopencv_imgproc -lopencv_features2d -lopencv_flann -lopencv_video   -L /home/jun/Programs/Xilinx2018.2/SDx/2018.2/target/aarch32-linux/lib -L/home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -lsds_lib -lxlnk_stub  -Wl,--end-group -o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/colordetect_zed.elf
/home/jun/Programs/Xilinx2018.2/SDK/2018.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin/../lib/gcc/arm-linux-gnueabihf/7.2.1/../../../../arm-linux-gnueabihf/bin/ld: cannot find -lopencv_videoio
collect2: error: ld returned 1 exit status
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling 'arm-linux-gnueabihf-g++    /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_rgb2hsv_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_colorthresholding_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_dilation_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_erosion_hpp.o /home/jun/workspace_sdx/colordetect_zed/Release/src/xf_colordetect_tb.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/xf_colordetect_accel.o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/portinfo.o -L/usr/local/arm/opencv-install/lib -lopencv_videoio -lopencv_core -lopencv_imgproc -lopencv_features2d -lopencv_flann -lopencv_video   -L /home/jun/Programs/Xilinx2018.2/SDx/2018.2/target/aarch32-linux/lib -L/home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -lsds_lib -lxlnk_stub  -Wl,--end-group -o /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/colordetect_zed.elf'
sds++ log file saved as /home/jun/workspace_sdx/colordetect_zed/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed

[sds.log](https://github.com/Xilinx/SDSoC-Tutorials/files/3318014/sds.log)

**Comment by sgrace-xlnx** [comment]
Hi @microlijun,

Looks like you're having an issue with Includes and Lib paths. In the tutorial, the OpenCV libraries being targeted are ones that are pre-built in the SDx install area (which is also what the Linux image uses). From your screenshots it looks like you're actually targeting local machine libraries and not the ones in the SYSROOT used by the platform. You're using 2018.2, so you will need to be targeting the 2018.2 compiled libraries to be used. I would double check that your new Zedboard platform has the appropriate SYSROOT and libraries provided. If not, you'd need to consult UG1146 again to make sure things are in order.

Also, the Zedboard is considerably smaller than the ZCU102 and will be limited on resources. A good way to check this is to look at the accelerator compilation reports and see what is predicted for utilization.

Hope this helps
Steve

**Comment by microlijun** [comment]
Hi Steve @sgrace-xlnx 

According to UG1233 --- Using the xfOpenCV Library on a non-reVISION Platform : "The OpenCV library is not provided by Xilinx for custom platforms. You are required to provide the library. "

![image](https://user-images.githubusercontent.com/29748336/60104453-827d0800-972f-11e9-8a26-accd91cf4097.png)

![image](https://user-images.githubusercontent.com/29748336/60104407-67aa9380-972f-11e9-8a94-261c4e3e5f4c.png)

So I included an opencv libraries cross-compiled by arm-none-linux-gnueabi-gcc. However, it seems that SDx can't find the libraries. I don't know why it doesn't work.

In your instruction, do you mean that I have to create a custom zed platform for this? 

Thanks for your help.

Jun

**Comment by sgrace-xlnx** [comment]
You will have to create a custom platform to execute OpenCV functions. The base Linux image of the Zedboard does not come with OpenCV pre-installed. This also means the SYSROOT needed for compilation needs to contain the OpenCV libraries. You'll have to create a new image using Petalinux and map it to a DSA. This can be found in UG1146.

**Comment by microlijun** [comment]
Hi @sgrace-xlnx 

The opencv include/lib path issue is solve. New errors come:

Link application ELF file
arm-linux-gnueabihf-g++     /home/jun/workspace_sdx/VideoFusion_zed/Release/src/guided_filter.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_accel.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_tb.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/thermal_target_accel.o /home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs/portinfo.o -L/opt/opencv-4.1.1/lib -lopencv_videoio -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_video -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs   -L /home/jun/Programs/Xilinx2018.2/SDx/2018.2/target/aarch32-linux/lib -L/home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -lsds_lib -lxlnk_stub  -Wl,--end-group -o /home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs/VideoFusion_zed.elf
/home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_tb.o: In function `guidedFilter(cv::Mat, cv::Mat, int, double)':
image_fusion_tb.cpp:(.text+0x128): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x26c): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x3d0): undefined reference to `cv::_InputArray::_InputArray(cv::MatExpr const&)'
image_fusion_tb.cpp:(.text+0x3e4): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x5bc): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x5d0): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x66c): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x680): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x71c): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x74c): undefined reference to `cv::_InputArray::_InputArray(cv::MatExpr const&)'
image_fusion_tb.cpp:(.text+0x760): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x8c8): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0xc04): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0xc34): undefined reference to `cv::_InputArray::_InputArray(cv::MatExpr const&)'
image_fusion_tb.cpp:(.text+0xc48): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0xdbc): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x1390): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x16d4): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x16e0): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x18c0): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x18cc): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x1a64): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
/home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_tb.o: In function `image_fusion(cv::Mat&, cv::Mat&, cv::Mat&)':
image_fusion_tb.cpp:(.text+0x2880): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
image_fusion_tb.cpp:(.text+0x2970): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text+0x2984): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'
/home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_tb.o: In function `main':
image_fusion_tb.cpp:(.text.startup+0x6b0): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
image_fusion_tb.cpp:(.text.startup+0x710): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'
collect2: error: ld returned 1 exit status
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling 'arm-linux-gnueabihf-g++     /home/jun/workspace_sdx/VideoFusion_zed/Release/src/guided_filter.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_accel.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/image_fusion_tb.o /home/jun/workspace_sdx/VideoFusion_zed/Release/src/thermal_target_accel.o /home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs/portinfo.o -L/opt/opencv-4.1.1/lib -lopencv_videoio -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_video -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs   -L /home/jun/Programs/Xilinx2018.2/SDx/2018.2/target/aarch32-linux/lib -L/home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -lsds_lib -lxlnk_stub  -Wl,--end-group -o /home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/swstubs/VideoFusion_zed.elf'
sds++ log file saved as /home/jun/workspace_sdx/VideoFusion_zed/Release/_sds/reports/sds.log
ERROR: [SdsCompiler 83-5004] Build failed
sds++ completed at Sat Jun 29 19:16:23 UTC 2019

**Comment by microlijun** [comment]
Hi, @sgrace-xlnx  @stsoe  @amantalwar04  @lmet321 
The opencv include/lib path issue is solved. 
New errors come,
error: /home/jun/workspace_sdx/colordetect_zed/Release/_sds/swstubs/colordetect_zed.elf uses VFP register arguments, /usr/local/arm/arm-opencv3.1/lib/libopencv_world.a(matrix.cpp.obj) does not

Do I need to any instruction at Linker Flags?
Thank you so much for your help.

[sds.log](https://github.com/Xilinx/SDSoC-Tutorials/files/3343414/sds.log)

**Comment by microlijun** [comment]
solved

**Comment by khalid17160** [comment]
@microlijun can u provide the step you used to run it for ZedBoard it would be a great help.
